### ISSUE TITLE
Arithmetic range errors

### ISSUE THREAD

**Issue by aheaume** [xuchunyang/eshell-z#2]
Hi!

Running any command produces `Arithmetic range error`s.

Running `GNU Emacs 25.0.50.1 (i686-pc-mingw32) of 2015-11-09` (on Windows).

``` shell
.emacs.d:master*? λ pwd
d:/src/dotfiles-emacs/.emacs.d
.emacs.d:master*? λ 
Arithmetic range error: "truncate", 1447160081.509
.emacs.d:master*? λ echo 'hi xuchunyang!'
hi xuchunyang!
.emacs.d:master*? λ 
Arithmetic range error: "truncate", 1447160095.6
.emacs.d:master*? λ 
```

Here's a backtrace:

```
Debugger entered--Lisp error: (range-error "truncate" 1447159905.182)
  truncate(1447159905.182)
  eshell-z--add()
  run-hooks(eshell-post-command-hook)
  eval((run-hooks (quote eshell-post-command-hook)))
  eshell-do-eval((run-hooks (quote eshell-post-command-hook)) nil)
  eshell-do-eval((progn (quote nil) (quote nil) (run-hooks (quote eshell-post-command-hook))) nil)
  (let ((eshell-current-handles (quote [nil (nil . 0) (nil . 0)])) eshell-current-subjob-p) (eshell-do-eval (quote (progn (quote nil) (quote nil) (run-hooks (quote eshell-post-command-hook)))) nil))
  eval((let ((eshell-current-handles (quote [nil (nil . 0) (nil . 0)])) eshell-current-subjob-p) (eshell-do-eval (quote (progn (quote nil) (quote nil) (run-hooks (quote eshell-post-command-hook)))) nil)))
  eshell-do-eval((let ((eshell-current-handles (quote [nil (nil . 0) (nil . 0)])) eshell-current-subjob-p) (eshell-do-eval (quote (progn (quote nil) (quote nil) (run-hooks (quote eshell-post-command-hook)))) nil)))
  eshell-resume-eval()
  eshell-eval-command((let ((eshell-current-handles (quote [nil (nil . 0) (nil . 0)])) eshell-current-subjob-p) (eshell-do-eval (quote (progn (quote nil) (quote nil) (run-hooks (quote eshell-post-command-hook)))) nil)) "ls")
  eshell-send-input(nil)
  funcall-interactively(eshell-send-input nil)
  call-interactively(eshell-send-input nil nil)
  command-execute(eshell-send-input)
```

How can I help you resolve this?

**Comment by xuchunyang** [comment]
Do you get the same error if just evaluate  `(truncate 1447159905.182)`?

**Comment by aheaume** [comment]
Yes.

`(truncate 144715990.182)` works, though.

**Comment by xuchunyang** [comment]
I don't know what causes the problem for you, but It looks like https://github.com/magit/magit/issues/1074.

**Comment by xuchunyang** [comment]
Oop, I'm not sure this is fixed, reopening...

**Comment by aheaume** [comment]
So, `truncate`, `cl-truncate`, etc. are broken on 32-bit systems for large numbers.

This _almost_ works:

``` emacs-lisp
(defun eshell-z--truncate (x)
  (condition-case nil
      (truncate x)
    (range-error
     (string-to-number (format-time-string "%s")))))
```

`(eshell-z--truncate 1447159905.182)` produces `1447159905.0` because `string-to-number` seems broken too.

**Comment by aheaume** [comment]
Thanks for 1d65a69, but it isn't enough because `string-to-number` and `string-to-int` are unfortunately broken on 32-bit systems for large numbers, and there's no sensible way to fix that.

```
(string-to-int "144715990")  ;=> 144715990
(string-to-int "1447159905") ;=> 1447159905.0
```

**Comment by xuchunyang** [comment]
I think we can just avoid to convert that large _number_ into number (that is, keep it as string), it should be easy, it is in number most because number is easy to compare. I will try this tomorrow.

**Comment by aheaume** [comment]
I was looking at the source to do just that, maybe you'll just have a PR to review & merge tomorrow ;) Thanks a lot

**Comment by xuchunyang** [comment]
> I was looking at the source to do just that, maybe you'll just have a PR to review & merge tomorrow ;)

I am very appreciated.
