### ISSUE TITLE
Autocompletion on directories

### ISSUE THREAD

**Issue by AlexChalk** [xuchunyang/eshell-z#8]
In the readme, you say 

> z supports basic tab completion, press TAB to complete on options and directories. 

Tab completion works for me on options, but not on directories. 
e.g. if I am in `~` and type `z week1` `CR`, z takes me to `~/projects/week1`, but if I type `z week1` `TAB`, nothing happens. Am I using the package correctly?

**Comment by xuchunyang** [comment]
The current Tab completion can only complete by prefix against all directories known by `z`, and all directories's full path are prefixed with `/`, thus you need to type something like `/usr/local` to get completion. However, I didn't find this completion is useful.

**Comment by AlexChalk** [comment]
I see. I think it works well as is, I was just unsure of how the functionality works. Maybe add this to the readme? 
Thanks for a great package.
